export interface VideoItem {
  id: string;
  title: string;
  description: string;
  channelTitle: string;
  channelId?: string;
  publishedAt: string;
  thumbnailUrl: string;
  duration?: string;
  durationSeconds?: number;
  viewCount?: string;
  likeCount?: string;
}

export interface SearchResult {
  items: VideoItem[];
  nextPageToken?: string | null;
  totalResults?: number;
  source: 'youtube-data-api' | 'fallback-search';
}

export interface TranscriptSegment {
  text: string;
  offset: number; // in milliseconds
  duration: number; // in milliseconds
}

export interface CaptionTrackInfo {
  languageCode: string;
  name: string;
  isAutoGenerated?: boolean;
}

export interface TranscriptResult {
  videoId: string;
  segments: TranscriptSegment[];
  availableLanguages: CaptionTrackInfo[];
  selectedLanguage: string;
  totalWords: number;
  plainText: string;
}

export interface AISummaryResult {
  summary: string;
  keyPoints: string[];
  chapters?: { timestamp: string; title: string; summary: string }[];
}
